<a href="https://colab.research.google.com/github/DhushyanthRavichandran/AI/blob/main/randomforest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Loan%20Status.csv")

In [ ]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
data.info

<bound method DataFrame.info of       Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No
1    LP001003    Male     Yes          1      Graduate            No
2    LP001005    Male     Yes          0      Graduate           Yes
3    LP001006    Male     Yes          0  Not Graduate            No
4    LP001008    Male      No          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
609  LP002978  Female      No          0      Graduate            No
610  LP002979    Male     Yes         3+      Graduate            No
611  LP002983    Male     Yes          1      Graduate            No
612  LP002984    Male     Yes          2      Graduate            No
613  LP002990  Female      No          0      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]>

In [ ]:
data.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [ ]:
data['Gender']

0        Male
1        Male
2        Male
3        Male
4        Male
        ...
609    Female
610      Male
611      Male
612      Male
613    Female
Name: Gender, Length: 614, dtype: object

In [ ]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
for i in data.columns:
  df=data[i].value_counts()
df

Y    422
N    192
Name: Loan_Status, dtype: int64

In [ ]:
data['Loan_Status'].value_counts()

Y    422
N    192
Name: Loan_Status, dtype: int64

In [ ]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
data.shape

(614, 13)

In [ ]:
data.dropna()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
data.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
type(data.columns)

pandas.core.indexes.base.Index

In [ ]:
data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
data['Loan_ID'].unique()

array(['LP001002', 'LP001003', 'LP001005', 'LP001006', 'LP001008',
       'LP001011', 'LP001013', 'LP001014', 'LP001018', 'LP001020',
       'LP001024', 'LP001027', 'LP001028', 'LP001029', 'LP001030',
       'LP001032', 'LP001034', 'LP001036', 'LP001038', 'LP001041',
       'LP001043', 'LP001046', 'LP001047', 'LP001050', 'LP001052',
       'LP001066', 'LP001068', 'LP001073', 'LP001086', 'LP001087',
       'LP001091', 'LP001095', 'LP001097', 'LP001098', 'LP001100',
       'LP001106', 'LP001109', 'LP001112', 'LP001114', 'LP001116',
       'LP001119', 'LP001120', 'LP001123', 'LP001131', 'LP001136',
       'LP001137', 'LP001138', 'LP001144', 'LP001146', 'LP001151',
       'LP001155', 'LP001157', 'LP001164', 'LP001179', 'LP001186',
       'LP001194', 'LP001195', 'LP001197', 'LP001198', 'LP001199',
       'LP001205', 'LP001206', 'LP001207', 'LP001213', 'LP001222',
       'LP001225', 'LP001228', 'LP001233', 'LP001238', 'LP001241',
       'LP001243', 'LP001245', 'LP001248', 'LP001250', 'LP001253',
       'LP001255', 'LP001256', 'LP001259', 'LP001263', 'LP001264',
       'LP001265', 'LP001266', 'LP001267', 'LP001273', 'LP001275',
       'LP001279', 'LP001280', 'LP001282', 'LP001289', 'LP001310',
       'LP001316', 'LP001318', 'LP001319', 'LP001322', 'LP001325',
       'LP001326', 'LP001327', 'LP001333', 'LP001334', 'LP001343',
       'LP001345', 'LP001349', 'LP001350', 'LP001356', 'LP001357',
       'LP001367', 'LP001369', 'LP001370', 'LP001379', 'LP001384',
       'LP001385', 'LP001387', 'LP001391', 'LP001392', 'LP001398',
       'LP001401', 'LP001404', 'LP001405', 'LP001421', 'LP001422',
       'LP001426', 'LP001430', 'LP001431', 'LP001432', 'LP001439',
       'LP001443', 'LP001448', 'LP001449', 'LP001451', 'LP001465',
       'LP001469', 'LP001473', 'LP001478', 'LP001482', 'LP001487',
       'LP001488', 'LP001489', 'LP001491', 'LP001492', 'LP001493',
       'LP001497', 'LP001498', 'LP001504', 'LP001507', 'LP001508',
       'LP001514', 'LP001516', 'LP001518', 'LP001519', 'LP001520',
       'LP001528', 'LP001529', 'LP001531', 'LP001532', 'LP001535',
       'LP001536', 'LP001541', 'LP001543', 'LP001546', 'LP001552',
       'LP001560', 'LP001562', 'LP001565', 'LP001570', 'LP001572',
       'LP001574', 'LP001577', 'LP001578', 'LP001579', 'LP001580',
       'LP001581', 'LP001585', 'LP001586', 'LP001594', 'LP001603',
       'LP001606', 'LP001608', 'LP001610', 'LP001616', 'LP001630',
       'LP001633', 'LP001634', 'LP001636', 'LP001637', 'LP001639',
       'LP001640', 'LP001641', 'LP001643', 'LP001644', 'LP001647',
       'LP001653', 'LP001656', 'LP001657', 'LP001658', 'LP001664',
       'LP001665', 'LP001666', 'LP001669', 'LP001671', 'LP001673',
       'LP001674', 'LP001677', 'LP001682', 'LP001688', 'LP001691',
       'LP001692', 'LP001693', 'LP001698', 'LP001699', 'LP001702',
       'LP001708', 'LP001711', 'LP001713', 'LP001715', 'LP001716',
       'LP001720', 'LP001722', 'LP001726', 'LP001732', 'LP001734',
       'LP001736', 'LP001743', 'LP001744', 'LP001749', 'LP001750',
       'LP001751', 'LP001754', 'LP001758', 'LP001760', 'LP001761',
       'LP001765', 'LP001768', 'LP001770', 'LP001776', 'LP001778',
       'LP001784', 'LP001786', 'LP001788', 'LP001790', 'LP001792',
       'LP001798', 'LP001800', 'LP001806', 'LP001807', 'LP001811',
       'LP001813', 'LP001814', 'LP001819', 'LP001824', 'LP001825',
       'LP001835', 'LP001836', 'LP001841', 'LP001843', 'LP001844',
       'LP001846', 'LP001849', 'LP001854', 'LP001859', 'LP001864',
       'LP001865', 'LP001868', 'LP001870', 'LP001871', 'LP001872',
       'LP001875', 'LP001877', 'LP001882', 'LP001883', 'LP001884',
       'LP001888', 'LP001891', 'LP001892', 'LP001894', 'LP001896',
       'LP001900', 'LP001903', 'LP001904', 'LP001907', 'LP001908',
       'LP001910', 'LP001914', 'LP001915', 'LP001917', 'LP001922',
       'LP001924', 'LP001925', 'LP001926', 'LP001931', 'LP001935',
       'LP001936', 'LP001938', 'LP001940', 'LP001945', 'LP001947',
       'LP001949', 'LP001953', 'LP001954', 'LP001955', 'LP001963',
       'LP001964', 'LP001972', 'LP001974', 'LP001977', 'LP001978',
       'LP001990', 'LP001993', 'LP001994', 'LP001996', 'LP001998',
       'LP002002', 'LP002004', 'LP002006', 'LP002008', 'LP002024',
       'LP002031', 'LP002035', 'LP002036', 'LP002043', 'LP002050',
       'LP002051', 'LP002053', 'LP002054', 'LP002055', 'LP002065',
       'LP002067', 'LP002068', 'LP002082', 'LP002086', 'LP002087',
       'LP002097', 'LP002098', 'LP002100', 'LP002101', 'LP002103',
       'LP002106', 'LP002110', 'LP002112', 'LP002113', 'LP002114',
       'LP002115', 'LP002116', 'LP002119', 'LP002126', 'LP002128',
       'LP002129', 'LP002130', 'LP002131', 'LP002137', 'LP002138',
       'LP002139', 'LP002140', 'LP002141', 'LP002142', 'LP002143',
       'LP002144', 'LP002149', 'LP002151', 'LP002158', 'LP002160',
       'LP002161', 'LP002170', 'LP002175', 'LP002178', 'LP002180',
       'LP002181', 'LP002187', 'LP002188', 'LP002190', 'LP002191',
       'LP002194', 'LP002197', 'LP002201', 'LP002205', 'LP002209',
       'LP002211', 'LP002219', 'LP002223', 'LP002224', 'LP002225',
       'LP002226', 'LP002229', 'LP002231', 'LP002234', 'LP002236',
       'LP002237', 'LP002239', 'LP002243', 'LP002244', 'LP002250',
       'LP002255', 'LP002262', 'LP002263', 'LP002265', 'LP002266',
       'LP002272', 'LP002277', 'LP002281', 'LP002284', 'LP002287',
       'LP002288', 'LP002296', 'LP002297', 'LP002300', 'LP002301',
       'LP002305', 'LP002308', 'LP002314', 'LP002315', 'LP002317',
       'LP002318', 'LP002319', 'LP002328', 'LP002332', 'LP002335',
       'LP002337', 'LP002341', 'LP002342', 'LP002345', 'LP002347',
       'LP002348', 'LP002357', 'LP002361', 'LP002362', 'LP002364',
       'LP002366', 'LP002367', 'LP002368', 'LP002369', 'LP002370',
       'LP002377', 'LP002379', 'LP002386', 'LP002387', 'LP002390',
       'LP002393', 'LP002398', 'LP002401', 'LP002403', 'LP002407',
       'LP002408', 'LP002409', 'LP002418', 'LP002422', 'LP002424',
       'LP002429', 'LP002434', 'LP002435', 'LP002443', 'LP002444',
       'LP002446', 'LP002447', 'LP002448', 'LP002449', 'LP002453',
       'LP002455', 'LP002459', 'LP002467', 'LP002472', 'LP002473',
       'LP002478', 'LP002484', 'LP002487', 'LP002489', 'LP002493',
       'LP002494', 'LP002500', 'LP002501', 'LP002502', 'LP002505',
       'LP002515', 'LP002517', 'LP002519', 'LP002522', 'LP002524',
       'LP002527', 'LP002529', 'LP002530', 'LP002531', 'LP002533',
       'LP002534', 'LP002536', 'LP002537', 'LP002541', 'LP002543',
       'LP002544', 'LP002545', 'LP002547', 'LP002555', 'LP002556',
       'LP002560', 'LP002562', 'LP002571', 'LP002582', 'LP002585',
       'LP002586', 'LP002587', 'LP002588', 'LP002600', 'LP002602',
       'LP002603', 'LP002606', 'LP002615', 'LP002618', 'LP002619',
       'LP002622', 'LP002624', 'LP002625', 'LP002626', 'LP002634',
       'LP002637', 'LP002640', 'LP002643', 'LP002648', 'LP002652',
       'LP002659', 'LP002670', 'LP002682', 'LP002683', 'LP002684',
       'LP002689', 'LP002690', 'LP002692', 'LP002693', 'LP002697',
       'LP002699', 'LP002705', 'LP002706', 'LP002714', 'LP002716',
       'LP002717', 'LP002720', 'LP002723', 'LP002729', 'LP002731',
       'LP002732', 'LP002734', 'LP002738', 'LP002739', 'LP002740',
       'LP002741', 'LP002743', 'LP002753', 'LP002755', 'LP002757',
       'LP002767', 'LP002768', 'LP002772', 'LP002776', 'LP002777',
       'LP002778', 'LP002784', 'LP002785', 'LP002788', 'LP002789',
       'LP002792', 'LP002794', 'LP002795', 'LP002798', 'LP002804',
       'LP002807', 'LP002813', 'LP002820', 'LP002821', 'LP002832',
       'LP002833', 'LP002836', 'LP002837', 'LP002840', 'LP002841',
       'LP002842', 'LP002847', 'LP002855', 'LP002862', 'LP002863',
       'LP002868', 'LP002872', 'LP002874', 'LP002877', 'LP002888',
       'LP002892', 'LP002893', 'LP002894', 'LP002898', 'LP002911',
       'LP002912', 'LP002916', 'LP002917', 'LP002925', 'LP002926',
       'LP002928', 'LP002931', 'LP002933', 'LP002936', 'LP002938',
       'LP002940', 'LP002941', 'LP002943', 'LP002945', 'LP002948',
       'LP002949', 'LP002950', 'LP002953', 'LP002958', 'LP002959',
       'LP002960', 'LP002961', 'LP002964', 'LP002974', 'LP002978',
       'LP002979', 'LP002983', 'LP002984', 'LP002990'], dtype=object)

In [ ]:
data['Loan_ID'].nunique()

614

In [ ]:
data['Loan_ID'].count()

614

In [ ]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df=label.fit_transform(data['Loan_Status'])

In [ ]:
df

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
'''onehot=OneHotEncoder(sparse=False)
df_1=np.array([df['Loan_Status']]).reshape(-1,1)
df1=onehot.fit_transform(df_1)
df1'''

"onehot=OneHotEncoder(sparse=False)\ndf_1=np.array([df['Loan_Status']]).reshape(-1,1)\ndf1=onehot.fit_transform(df_1)\ndf1"

In [ ]:
data['Gender']=data['Gender'].map({"male":1,"female":0})
data['Married']=data['Married'].map({"Yes":1,"No":0})
data['Education']=data['Education'].map({"Graduate":1,"Not Graduate":0})
data['Self_Employed']=data['Self_Employed'].map({"Yes":1,"No":0})
data['Property_Area']=data['Property_Area'].map({"Urban":1,"Rural":0,'Semiurban':2})
data['Loan_Status']=data['Loan_Status'].map({"Y":1,"N":0})

data['Dependents']=data['Dependents'].map({"0":0,"1":1,"2":2,"3+":3})

In [ ]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,NaN,0.0,0.0,1,0.0,5849,0.0,NaN,360.0,1.0,1,1
1,LP001003,NaN,1.0,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0
2,LP001005,NaN,1.0,0.0,1,1.0,3000,0.0,66.0,360.0,1.0,1,1
3,LP001006,NaN,1.0,0.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,1
4,LP001008,NaN,0.0,0.0,1,0.0,6000,0.0,141.0,360.0,1.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,NaN,0.0,0.0,1,0.0,2900,0.0,71.0,360.0,1.0,0,1
610,LP002979,NaN,1.0,3.0,1,0.0,4106,0.0,40.0,180.0,1.0,0,1
611,LP002983,NaN,1.0,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,1
612,LP002984,NaN,1.0,2.0,1,0.0,7583,0.0,187.0,360.0,1.0,1,1
613,LP002990,NaN,0.0,0.0,1,1.0,4583,0.0,133.0,360.0,0.0,2,0

In [ ]:
rev_null=['Gender','Married','Dependents','Self_Employed','Credit_History','LoanAmount','Loan_Amount_Term']
data[rev_null]=data[rev_null].replace({np.nan:data['Gender'].mode(),
                                       np.nan:data['Married'].mode(),
                                       np.nan:data['Dependents'].mode(),
                                       np.nan:data['Self_Employed'].mode(),
                                       np.nan:data['Credit_History'].mode(),
                                       np.nan:data['LoanAmount'].mean(),
                                       np.nan:data['Loan_Amount_Term'].mean()


                                       })

In [ ]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,342.0,0.0,0.0,1,0.0,5849,0.0,342.0,360.0,1.0,1,1
1,LP001003,342.0,1.0,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0
2,LP001005,342.0,1.0,0.0,1,1.0,3000,0.0,66.0,360.0,1.0,1,1
3,LP001006,342.0,1.0,0.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,1
4,LP001008,342.0,0.0,0.0,1,0.0,6000,0.0,141.0,360.0,1.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,342.0,0.0,0.0,1,0.0,2900,0.0,71.0,360.0,1.0,0,1
610,LP002979,342.0,1.0,3.0,1,0.0,4106,0.0,40.0,180.0,1.0,0,1
611,LP002983,342.0,1.0,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,1
612,LP002984,342.0,1.0,2.0,1,0.0,7583,0.0,187.0,360.0,1.0,1,1
613,LP002990,342.0,0.0,0.0,1,1.0,4583,0.0,133.0,360.0,0.0,2,0

In [ ]:
  data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
x=data.drop(columns=['Loan_ID','Loan_Status'])
y=data['Loan_Status']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

X_train

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
244,342.0,1.0,0.0,0,0.0,3406,4417.0,123.0,360.0,1.0,2
393,342.0,1.0,2.0,0,0.0,1993,1625.0,113.0,180.0,1.0,2
310,342.0,0.0,0.0,1,0.0,2917,0.0,84.0,360.0,1.0,2
408,342.0,1.0,1.0,1,0.0,8300,0.0,152.0,300.0,0.0,2
572,342.0,1.0,2.0,1,0.0,16666,0.0,275.0,360.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
71,342.0,1.0,2.0,0,1.0,1875,1875.0,97.0,360.0,1.0,2
106,342.0,1.0,2.0,1,0.0,11417,1126.0,225.0,360.0,1.0,1
270,342.0,0.0,0.0,1,0.0,3237,0.0,30.0,360.0,1.0,1
435,342.0,342.0,342.0,1,0.0,10047,0.0,342.0,240.0,1.0,2
102,342.0,1.0,342.0,1,0.0,13650,0.0,342.0,360.0,1.0,1

In [ ]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
rfc=RandomForestClassifier(criterion='entropy',random_state=42)
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [ ]:
from inspect import classify_class_attrs
y_pred_test=rfc.predict(X_train)
print(classification_report(y_train,y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       120
           1       1.00      1.00      1.00       291

    accuracy                           1.00       411
   macro avg       1.00      1.00      1.00       411
weighted avg       1.00      1.00      1.00       411